### ISSUE TITLE
dimensions

### ISSUE THREAD

**Issue by axlekb** [ankane/rollup#14]
I've been thinking about using this gem to move aggregation queries of historical transactions across multiple tenants to the background.  Think product or customer specific rollups.

Every time I start I pull back because the dimension support is via `jsonb`.  While possible, it makes ActiveRecord joins more difficult.

I was wondering if you every considered having a single polymorphic dimensional column to easily allow other joins.

P.S. Thanks for all you've built

**Comment by ankane** [comment]
Hi @axlekb, it's an interesting idea, but I don't think it's worth additional complexity (as I'm not sure it's common to join against rollups and already possible when needed as you mentioned).
