### ISSUE TITLE
Generate initial data in batches?

### ISSUE THREAD

**Issue by marckohlbrugge** [ankane/rollup#2]
First of all thank you @ankane for building this gem and all the other ones you've released. As a bootstrapping founder with a very small team your work has been a life-saver.

We're currently implementing Rollup for our job board and we've got a ton of Ahoy Events in our database. Unfortunately  calling the rollup query straight up is timing out. PostgreSQL killing the connection, etc. And while I'm sure there's a way to configure my server so it will stop doing that, I was wondering if there's an easier way to split up the initial data generation by splitting it up in smaller parts?

Here's what's timing out:

```ruby
Ahoy::Event.where(name: "Visited jobs post").group_prop(:post_id).rollup("Visited jobs post", column: :time, interval: :day)
```

Here's what I'm considering doing instead.

```ruby
cutoff = 48
Ahoy::Event.where("time::date < ?", cutoff.months.ago).where(name: "Visited jobs post").group_prop(:post_id).rollup("Visited jobs post", column: :time, interval: :day)
```

After each run we decrease`cutoff`. Rollup seems smart enough not to recalculate days it already processed.

My question is whether this is the right approach or if you foresee any problems with this? I want to avoid missing data on partial days, etc.

**Comment by ankane** [comment]
Hey @marckohlbrugge, that sounds like a good approach. Rollup will recalculate the last interval that has data on each run, so you shouldn't end up with any partial days.

**Comment by E1337Kat** [comment]
Hello, I know this is an old closed issue, but though I would add a comment on how I've implemented batching for my company's app so others could make use of it if desired. In a data migration I have added this:

```ruby
# db/data/20240807203526_generate_historical_rollup_data.rb

class GenerateHistoricalRollupData < ActiveRecord::Migration[6.1]
  def up
    @begin_date = SomeModel.minimum(:created_at).beginning_of_day
    while @begin_date < SomeModel.maximum(:created_at).beginning_of_day
      @end_date = @begin_date + 1.day
      Background::RollupGeneration.enqueue(start: @begin_date, stop: @end_date)
      @begin_date = @end_date
    end
  end

  def down
    Rollup.delete_all
  end
end
```

and then the background job builds the range and actually does the rollup on ranges:

```ruby
# app/services/background/rollup_generation.rb

module Background
  class RollupGeneration
    def self.enqueue(options)
      Delayed::Job.enqueue(new(options), queue: "fast")
    end

    def initialize(options)
      @start = options[:start]
      @stop = options[:stop]
      @range = @start..@stop
    end

    def perform
      SomeModel
        .group(:account_id, :company_id)
        .rollup("account_company_job_counts", range: @range)
    end
  end
end
```

This seemed to work pretty well on my local environment and staging. Our prod environment has 10m Job objects with some days having as many as 3000 jobs created, and the delayed workers were mostly able to handle everything just fine.

**Comment by marckohlbrugge** [comment]
@E1337Kat It seems like this is running synchronously right? Otherwise the `while` wouldn't work as expected.

**Comment by E1337Kat** [comment]
The `Delayed::Job.enqueue(new(options), queue: "fast")` enqueues a background job that runs asynchronously from the main application thread/migration thread. The while is just setting up the jobs for each day at a time. So the migration created x number of background jobs that ran in separate workers to generate and save that day's data. And the data was created correctly as far as I can tell.
