### ISSUE TITLE
Connect to different database?

### ISSUE THREAD

**Issue by bobdutch** [ankane/rollup#8]
I'm using a Rails app with multiple databases. The Rollup class in the gem inherits from ActiveRecord::Base so it uses the primary database connection. Is there a way I can change the database connection or superclass for the model? If not I think it would be a good feature. Thanks.

**Comment by ankane** [comment]
Hey @bobdutch, you should be able to create an initializer with:

```ruby
Rollup.establish_connection(:otherdb)
```

**Comment by bobdutch** [comment]
That's perfect. Thank you!

**Comment by dudadornelles** [comment]
Could it read from one db but write on another? Thinking replica for reads primary for writes

**Comment by ankane** [comment]
Hey @dudadornelles, please create a new issue for this.
