### ISSUE TITLE
Rollup on an associatated model column

### ISSUE THREAD

**Issue by cimm** [ankane/rollup#9]
Is it possible to use a column from an associated model as the rollup column?

Take a `User` model belonging to an `Account` model and I want to count the users by account creation time as an example. I tried the following two but Rollup does not seem to understand.

```ruby
User.includes(:account).rollup(:users_per_month, column: 'accounts.created_at', interval: :month)
User.includes(:account).rollup(:users_per_month, column: {account: :created_at}, interval: :month)
```

Thank you!

**Comment by ankane** [comment]
Hey @cimm, it should work with `joins` instead of `includes`:

```ruby
User.joins(:account).rollup(:users_per_month, column: 'accounts.created_at', interval: :month)
```

**Comment by cimm** [comment]
Indeed, that does work! I tried with `joins` but had another typo I missed. Sorry!

Thank you for the great gem (and your "[Securing Sensitive Data in Rails](https://ankane.org/sensitive-data-rails)" which I really liked).

**Comment by ankane** [comment]
No worries, added a test for it in 66632b720580cc2a8a0173b2b3823318b2a82ebd. And thanks!
